test_clean:
  _target_: src.datasets.LibrispeechDataset
  part: "test-clean"
  instance_transforms: ${transforms.instance_transforms.inference}
test_other:
  _target_: src.datasets.LibrispeechDataset
  part: "test-other"
  instance_transforms: ${transforms.instance_transforms.inference}
