train:
  _target_: src.datasets.LibreSpeechDataset
  name: "train-clean-100"
  instance_transforms: ${transforms.instance_transforms.train}
test:
  _target_: src.datasets.LibreSpeechDataset
  name: "test-clean"
  instance_transforms: ${transforms.instance_transforms.inference}
